name: Run Weather Fetch Script

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  weather-fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the weather fetcher script
      run: |
        python api.py  # Now the file is in the root directory
      env:
        API_KEY: "8de3885a43c2983c713269e2b4f26ac2"  # Set the API key here
