name: Weather Data Fetcher

on:
  push:
    branches:
      - main  # Trigger the workflow when a push is made to the main branch
  schedule:
    - cron: '*/2 * * * *'  # This will run the job every 2 minutes

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out the repository to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Set Python version as required

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure the dependencies are listed in requirements.txt

      - name: Run the script
        run: |
          python api/api.py  # Run your script located in the 'api' folder
